title: Yourname's Homepage
page-top-title: Yourname
top-section-bg-text: Nothing is True. Everything is permitted.
home-subtitle: 吴佳琦&ensp;|&ensp;华中科技大学
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
